import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "../components/sharedd/Footer";
import Navbarr from "../components/sharedd/Navbarr";
import Providers from "@/lib/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Navbarr />
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
